# SPDX-FileCopyrightText: 2026 Jerin Joy
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "JumpStart"
SPDX-PackageSupplier = "Jerin Joy"
SPDX-PackageDownloadLocation = "https://github.com/rivosinc/JumpStart"

[[annotations]]
path = ["CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Meta Platforms, Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["Cargo.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Jerin Joy"
SPDX-License-Identifier = "Apache-2.0"
