/*
 * SPDX-FileCopyrightText: 2026 Jerin Joy
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// Import generated data structures from the single inclusion point.
// This gives us the `thread_attributes` struct definition.
use crate::generated::thread_attributes;

// --- External Assembly Linkage ---
// These functions are generated by scripts/generate_diag_sources.py.
// They directly access the 'tp' (thread pointer) register to retrieve
// hart-local attributes or use 'a0' for CPU ID lookups.

unsafe extern "C" {
    // M-mode Accessors (defined in .jumpstart.cpu.text.mmode)
    pub fn get_thread_attributes_cpu_id_from_mmode() -> u8;
    pub fn get_thread_attributes_physical_cpu_id_from_mmode() -> u8;
    pub fn get_thread_attributes_current_mode_from_mmode() -> u8;
    pub fn get_thread_attributes_current_v_bit_from_mmode() -> u8;
    pub fn get_thread_attributes_trap_override_struct_address_from_mmode() -> u64;
    pub fn get_thread_attributes_smode_setup_done_from_mmode() -> u8;
    pub fn get_thread_attributes_num_context_saves_remaining_in_mmode_from_mmode() -> u8;
    pub fn get_thread_attributes_num_context_saves_remaining_in_smode_from_mmode() -> u8;
    pub fn get_thread_attributes_marchid_from_mmode() -> u64;
    pub fn get_thread_attributes_mimpid_from_mmode() -> u64;
    pub fn get_thread_attributes_bookend_magic_number_from_mmode() -> u64;

    // S-mode Accessors (defined in .jumpstart.cpu.text.smode)
    pub fn get_thread_attributes_cpu_id_from_smode() -> u8;
    pub fn get_thread_attributes_physical_cpu_id_from_smode() -> u8;
    pub fn get_thread_attributes_current_mode_from_smode() -> u8;
    pub fn get_thread_attributes_current_v_bit_from_smode() -> u8;
    pub fn get_thread_attributes_trap_override_struct_address_from_smode() -> u64;
    pub fn get_thread_attributes_vsmode_setup_done_from_smode() -> u8;
    pub fn get_thread_attributes_num_context_saves_remaining_in_mmode_from_smode() -> u8;
    pub fn get_thread_attributes_num_context_saves_remaining_in_smode_from_smode() -> u8;
    pub fn get_thread_attributes_marchid_from_smode() -> u64;
    pub fn get_thread_attributes_mimpid_from_smode() -> u64;
    pub fn get_thread_attributes_bookend_magic_number_from_smode() -> u64;

    // Cross-CPU Attribute Lookups
    pub fn get_thread_attributes_for_cpu_id_from_mmode(cpu_id: u8) -> *mut thread_attributes;
    pub fn get_thread_attributes_for_cpu_id_from_smode(cpu_id: u8) -> *mut thread_attributes;

    // Failure paths defined in assembly
    pub fn jumpstart_mmode_fail() -> !;
    pub fn jumpstart_smode_fail() -> !;
    pub fn jumpstart_vsmode_fail() -> !;
}

// --- Safe Rust Wrappers ---
// These provide an ergonomic way to access the current hart's attributes.

pub struct CurrentHart;

impl CurrentHart {
    /// Returns the logical CPU ID of the current hart.
    #[inline]
    pub fn cpu_id() -> u8 {
        unsafe { get_thread_attributes_cpu_id_from_smode() }
    }

    /// Returns the physical CPU ID of the current hart.
    #[inline]
    pub fn physical_cpu_id() -> u8 {
        unsafe { get_thread_attributes_physical_cpu_id_from_smode() }
    }

    /// Returns the current execution mode (PRV_S, PRV_M, etc.).
    #[inline]
    pub fn mode() -> u8 {
        unsafe { get_thread_attributes_current_mode_from_smode() }
    }

    /// Returns the current virtualization bit.
    #[inline]
    pub fn v_bit() -> u8 {
        unsafe { get_thread_attributes_current_v_bit_from_smode() }
    }

    /// Returns the address of the trap override structure for the current hart.
    #[inline]
    pub fn trap_override_address() -> u64 {
        unsafe { get_thread_attributes_trap_override_struct_address_from_smode() }
    }
}

// --- Legacy C API Replacements ---
// These functions export the symbols expected by the existing C code/assembly.

/// Returns the physical CPU ID for a given logical CPU ID in Machine Mode.
///
/// Replaces `get_physical_cpu_id_for_cpu_id_from_mmode` in `thread_attributes.mmode.c`.
#[unsafe(link_section = ".jumpstart.cpu.text.mmode")]
#[unsafe(no_mangle)]
pub extern "C" fn get_physical_cpu_id_for_cpu_id_from_mmode(cpu_id: u8) -> u8 {
    // Get the thread attributes struct address for the given cpu_id
    let thread_attributes_ptr = unsafe { get_thread_attributes_for_cpu_id_from_mmode(cpu_id) };

    // Safety: The pointer returned by the assembly getter is checked for bounds.
    unsafe { (*thread_attributes_ptr).physical_cpu_id }
}

/// Returns the physical CPU ID for a given logical CPU ID in Supervisor Mode.
///
/// Replaces `get_physical_cpu_id_for_cpu_id_from_smode` in `thread_attributes.smode.c`.
#[unsafe(link_section = ".jumpstart.cpu.text.smode")]
#[unsafe(no_mangle)]
pub extern "C" fn get_physical_cpu_id_for_cpu_id_from_smode(cpu_id: u8) -> u8 {
    // Get the thread attributes struct address for the given cpu_id
    let thread_attributes_ptr = unsafe { get_thread_attributes_for_cpu_id_from_smode(cpu_id) };

    // Safety: Similar to the M-mode version, we dereference the pointer to get the field.
    unsafe { (*thread_attributes_ptr).physical_cpu_id }
}
